# Generated by Django 5.2.17 on 2026-09-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_alter_rejectreason_options_alter_skillzone_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='referral_source',
            field=models.CharField(blank=True, choices=[('job_board', 'Job Boards'), ('company_career_site', 'Company Career Site'), ('social_media', 'Social Media'), ('employee_referral', 'Employee Referral'), ('recruiter_headhunter', 'Recruiter / Headhunter'), ('search_engine', 'Search Engine'), ('college_university', 'College or University'), ('advertisement_event', 'Advertisement / Event'), ('other', 'Other')], max_length=20, null=True, verbose_name='How Did You Hear About Us?'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='referral_source_other',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Please Specify'),
        ),
        migrations.AddField(
            model_name='historicalcandidate',
            name='referral_source',
            field=models.CharField(blank=True, choices=[('job_board', 'Job Boards'), ('company_career_site', 'Company Career Site'), ('social_media', 'Social Media'), ('employee_referral', 'Employee Referral'), ('recruiter_headhunter', 'Recruiter / Headhunter'), ('search_engine', 'Search Engine'), ('college_university', 'College or University'), ('advertisement_event', 'Advertisement / Event'), ('other', 'Other')], max_length=20, null=True, verbose_name='How Did You Hear About Us?'),
        ),
        migrations.AddField(
            model_name='historicalcandidate',
            name='referral_source_other',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Please Specify'),
        ),
    ]
