# Generated by Django 5.2.17 on 2026-09-29 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_remove_policy_specific_employees_policy_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['id'], 'permissions': (('change_ownprofile', 'Update own profile'), ('view_ownprofile', 'View Own Profile'))},
        ),
    ]
