# Generated by Django 5.2.17 on 2026-09-29 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_assetrequestcomment'),
        ('employee', '0008_alter_employee_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('issue_description', models.TextField(max_length=255, verbose_name='Description')),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Returned', 'Returned')], default='Requested', max_length=30)),
                ('resolved_date', models.DateField(blank=True, null=True, verbose_name='Resolved Date')),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='asset.assetassignment', verbose_name='Asset Allocation')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('requested_employee_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_service_requests', to='employee.employee', verbose_name='Requested By')),
                ('resolved_by_employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_service_requests', to='employee.employee', verbose_name='Resolved By')),
            ],
            options={
                'verbose_name': 'Asset Service Request',
                'verbose_name_plural': 'Asset Service Requests',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AssetServiceRequestNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('note', models.TextField(verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='asset.assetservicerequest')),
            ],
            options={
                'verbose_name': 'Service Request Note',
                'verbose_name_plural': 'Service Request Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
