# Generated by Django 5.2.17 on 2026-09-28 10:29

import project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_timesheet_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='allocated_hours',
            field=models.CharField(blank=True, default='00:00', max_length=10, null=True, validators=[project.models.validate_time_format], verbose_name='Allocated Hours'),
        ),
    ]
